"""Load an existing staging JSON document without reopening Excel."""

import argparse
import json
from pathlib import Path
import sys

from .cli import add_load_arguments, execute_payload


def main(argv=None):
    parser = argparse.ArgumentParser(description="Load transformed quotation JSON into PostgreSQL")
    parser.add_argument("input", type=Path, help="JSON generated by python -m etl.transform")
    add_load_arguments(parser)
    args = parser.parse_args(argv)
    try:
        payload = json.loads(args.input.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        parser.exit(2, f"Unable to read Transform JSON: {type(exc).__name__}\n")
    return execute_payload(payload, args, parser)


if __name__ == "__main__":
    sys.exit(main())
