-- PostgreSQL schema for the marine quotation data platform.
-- Schema version: 2

BEGIN;

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE contacts (
    contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    contact_name TEXT,
    telephone TEXT,
    email TEXT,
    CONSTRAINT fk_contacts_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE RESTRICT
);

CREATE TABLE vessels (
    vessel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    vessel_name TEXT,
    hull_no TEXT,
    steering_gear_type TEXT,
    main_pump_type TEXT,
    servo_pump_type TEXT,
    CONSTRAINT fk_vessels_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE RESTRICT
);

CREATE TABLE quotations (
    quotation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_ref_no TEXT NOT NULL,
    quotation_type TEXT NOT NULL,
    quotation_year INTEGER,
    sequence_no INTEGER,
    suffix TEXT,
    customer_id INTEGER NOT NULL,
    contact_id INTEGER,
    quotation_date DATE,
    subject TEXT,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    document_total_amount NUMERIC(14, 2),
    lead_time_text TEXT,
    delivery_terms TEXT,
    payment_terms TEXT,
    additional_terms TEXT,
    CONSTRAINT uq_quotations_ref_no UNIQUE (quotation_ref_no),
    CONSTRAINT chk_quotations_type
        CHECK (quotation_type IN ('M', 'O')),
    CONSTRAINT chk_quotations_year
        CHECK (quotation_year IS NULL OR quotation_year >= 2000),
    CONSTRAINT chk_quotations_sequence
        CHECK (sequence_no IS NULL OR sequence_no > 0),
    CONSTRAINT chk_quotations_document_total
        CHECK (
            document_total_amount IS NULL
            OR document_total_amount >= 0
        ),
    CONSTRAINT fk_quotations_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_quotations_contact
        FOREIGN KEY (contact_id)
        REFERENCES contacts (contact_id)
        ON DELETE SET NULL
);

CREATE TABLE quotation_vessels (
    quotation_id INTEGER NOT NULL,
    vessel_id INTEGER NOT NULL,
    quoted_vessel_name TEXT,
    quoted_hull_no TEXT,
    CONSTRAINT pk_quotation_vessels
        PRIMARY KEY (quotation_id, vessel_id),
    CONSTRAINT fk_quotation_vessels_quotation
        FOREIGN KEY (quotation_id)
        REFERENCES quotations (quotation_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_quotation_vessels_vessel
        FOREIGN KEY (vessel_id)
        REFERENCES vessels (vessel_id)
        ON DELETE RESTRICT
);

CREATE TABLE quotation_items (
    quotation_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id INTEGER NOT NULL,
    line_no INTEGER,
    line_text_raw TEXT,
    item_type TEXT NOT NULL DEFAULT 'UNKNOWN',
    item_name TEXT,
    description TEXT,
    part_no TEXT,
    quantity INTEGER,
    quantity_unit TEXT,
    unit_price NUMERIC(14, 2),
    base_amount NUMERIC(14, 2),
    discount_rate NUMERIC(5, 2),
    quoted_amount NUMERIC(14, 2),
    remark TEXT,
    CONSTRAINT chk_quotation_items_type
        CHECK (item_type IN (
            'PART', 'KIT', 'SERVICE', 'EXPENSE', 'OTHER', 'UNKNOWN'
        )),
    CONSTRAINT chk_quotation_items_line_no
        CHECK (line_no IS NULL OR line_no > 0),
    CONSTRAINT chk_quotation_items_quantity
        CHECK (quantity IS NULL OR quantity >= 0),
    CONSTRAINT chk_quotation_items_unit_price
        CHECK (unit_price IS NULL OR unit_price >= 0),
    CONSTRAINT chk_quotation_items_base_amount
        CHECK (base_amount IS NULL OR base_amount >= 0),
    CONSTRAINT chk_quotation_items_discount_rate
        CHECK (
            discount_rate IS NULL
            OR discount_rate BETWEEN 0 AND 100
        ),
    CONSTRAINT chk_quotation_items_quoted_amount
        CHECK (quoted_amount IS NULL OR quoted_amount >= 0),
    CONSTRAINT fk_quotation_items_quotation
        FOREIGN KEY (quotation_id)
        REFERENCES quotations (quotation_id)
        ON DELETE CASCADE
);

CREATE TABLE kit_component_groups (
    kit_component_group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kit_quotation_item_id INTEGER NOT NULL,
    group_type TEXT NOT NULL,
    group_name_raw TEXT NOT NULL,
    equipment_model TEXT,
    equipment_quantity INTEGER,
    equipment_unit TEXT,
    group_amount NUMERIC(14, 2),
    CONSTRAINT chk_kit_component_groups_type
        CHECK (
            group_type IN (
                'MAIN_PUMP', 'SERVO_PUMP', 'LINE_FILTER', 'OTHERS'
            )
        ),
    CONSTRAINT chk_kit_component_groups_equipment_quantity
        CHECK (
            equipment_quantity IS NULL
            OR equipment_quantity >= 0
        ),
    CONSTRAINT chk_kit_component_groups_amount
        CHECK (group_amount IS NULL OR group_amount >= 0),
    CONSTRAINT fk_kit_component_groups_quotation_item
        FOREIGN KEY (kit_quotation_item_id)
        REFERENCES quotation_items (quotation_item_id)
        ON DELETE CASCADE
);

CREATE TABLE kit_components (
    kit_component_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kit_component_group_id INTEGER NOT NULL,
    line_no INTEGER,
    part_name TEXT,
    part_no TEXT,
    quantity INTEGER,
    quantity_unit TEXT,
    unit_price NUMERIC(14, 2),
    amount NUMERIC(14, 2),
    remark TEXT,
    CONSTRAINT chk_kit_components_line_no
        CHECK (line_no IS NULL OR line_no > 0),
    CONSTRAINT chk_kit_components_quantity
        CHECK (quantity IS NULL OR quantity >= 0),
    CONSTRAINT chk_kit_components_unit_price
        CHECK (unit_price IS NULL OR unit_price >= 0),
    CONSTRAINT chk_kit_components_amount
        CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT fk_kit_components_component_group
        FOREIGN KEY (kit_component_group_id)
        REFERENCES kit_component_groups (kit_component_group_id)
        ON DELETE CASCADE
);

CREATE TABLE service_details (
    quotation_id INTEGER PRIMARY KEY,
    working_place TEXT,
    service_engineer_count INTEGER,
    supporting_worker_count INTEGER,
    working_days INTEGER,
    includes_travel_days BOOLEAN,
    working_details TEXT,
    steering_gear_type TEXT,
    main_pump_type TEXT,
    servo_pump_type TEXT,
    CONSTRAINT chk_service_details_engineers
        CHECK (
            service_engineer_count IS NULL
            OR service_engineer_count >= 0
        ),
    CONSTRAINT chk_service_details_workers
        CHECK (
            supporting_worker_count IS NULL
            OR supporting_worker_count >= 0
        ),
    CONSTRAINT chk_service_details_days
        CHECK (working_days IS NULL OR working_days >= 0),
    CONSTRAINT fk_service_details_quotation
        FOREIGN KEY (quotation_id)
        REFERENCES quotations (quotation_id)
        ON DELETE CASCADE
);

-- Foreign-key indexes improve joins and parent-row delete checks.
CREATE INDEX idx_contacts_customer_id
    ON contacts (customer_id);

CREATE INDEX idx_vessels_customer_id
    ON vessels (customer_id);

CREATE INDEX idx_quotations_customer_id
    ON quotations (customer_id);

CREATE INDEX idx_quotations_contact_id
    ON quotations (contact_id);

CREATE INDEX idx_quotation_vessels_vessel_id
    ON quotation_vessels (vessel_id);

CREATE INDEX idx_quotation_items_quotation_id
    ON quotation_items (quotation_id);

CREATE INDEX idx_kit_component_groups_quotation_item_id
    ON kit_component_groups (kit_quotation_item_id);

CREATE INDEX idx_kit_components_component_group_id
    ON kit_components (kit_component_group_id);

COMMIT;
